server:
  port: 8081

spring:
  profiles:
    include: secret
    active: develop
  #    active: prod
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
springfox:
  documentation:
    swagger-ui:
      base-url: /api
    swagger:
      v2:
        path: /api
---
spring:
  config:
    activate:
      on-profile: develop

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:mysql://localhost:3306/fns?allowPublicKeyRetrieval=true
    # test 부분을 자신이 원하는 것으로 바꾸시면 됩니다.
    username: ssafy # username과 password는 자신의 설정에 맞게
    password: ssafy
    driver-class-name: com.mysql.jdbc.Driver
#  datasource:
#    url: jdbc:mysql://localhost:3306/fns
#    # test 부분을 자신이 원하는 것으로 바꾸시면 됩니다.
#    username: root # username과 password는 자신의 설정에 맞게
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create # 어플리케이션을 시작할 때 데이터베이스를 초기화하고 다시 테이블 생성
    properties:
      hibernate:
        format_sql: true # 실행되는 query를 보여줌
        show_sql: true
      logging.level:
        org.hibernate.SQL: debug

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://localhost:3000/oauth/kakao/callback
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me

  redis:
    host: 127.0.0.1
    port: 6379
